### ISSUE TITLE
Two projects 

### ISSUE THREAD

**Issue by HarshEcka** [Upliner/CharMorph#2]
It's good that different people have different ideas of approaching things and but in the case of MBlab ...it kinds of feel unjustified to the work ..Two developers having the common goal of using MBlab for creating game based characters but working differently...I think you and the person who revived MBLAB project should work together. He has a sound idea of shaders and he is reluctant of improving the shader...You on the other hand have the command over the coding....In this way the MBLAB will quickly and continuously evolve... Just a thought...

**Comment by Upliner** [comment]
I will try to help MB-Lab project but I really need CharMorph too because MB-Lab is inconvenient for me in many ways and when I started to estimate how much needs to be changed I realized that it will be easier to rewrite everything from scratch.
Also CharMorph helps my small team in developing new characters, maybe we'll be able to port them into MB-Lab soon.
